# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

schedules:
  - cron: "0 9 1 * *"
    displayName: Monthly build
    branches:
      include:
        - master
    always: true

strategy:
  matrix:
    "Ubuntu":
      image: "ubuntu-latest"
    "Windows Server":
      image: "windows-latest"

pool:
  vmImage: "$(image)"

steps:
  - task: UseNode@1
    inputs:
      version: "18.x"
    displayName: "Install Node.js"

  - script: "npm i -g yarn"
    displayName: "Install yarn"

  - script: "yarn"
    displayName: "Invoke yarn"

  - script: "node cli -h"
    displayName: "Invoke cli.js"
